name: Get file and author data, validate and update internal links

on:
  push:
    branches: ["dev"]

jobs:
  update_configs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        shell: bash
        run: cd utils/js && npm ci

      - name: Get file and Author data
        run: node utils/js/get_file_author_data.js

      - name: Validate and Update links
        run: node utils/js/validate_update_internal_links.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: update file and author data, validate and update internal links
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: file-author-data-lint
          delete-branch: true
          title: "[BOT] Update file and author data"
          body: |
            - File and author data updated, validated and updated internal links on merge to dev
          labels: |
            autogenerated
          reviewers: smk762, gcharang
          draft: false
